auth:
    accesstokenttl: 20m
    countattempt: 5
    limitauthttl: 30m
    refreshtokenttl: 24h
    secure: false
cache:
    ttl: 3600s
http:
    host: http://localhost
    maxheaderbytes: 1
    port: 8080
    readtimeout: 10s
    servicename: api-service
    writetimeout: 10s
limiter:
    burst: 20
    rps: 10
    ttl: 10m
order:
    delay: 24h
    term: 336h
postgres:
    dbname: route
    host: 127.0.0.1
    port: 5432
    sslmode: disable
    username: postgres
redis:
    db: 0
    host: 192.168.5.153
    port: 6379
urgency:
    high: 24h0m0s
    middle: 72h0m0s
