http:
    serviceName: "api-service"
    host: "http://localhost"
    port: 8080
    maxHeaderBytes: 1
    readTimeout: 10s
    writeTimeout: 10s

cache:
    ttl: 3600s

auth:
    accessTokenTTL: 20m
    refreshTokenTTL: 12h
    limitAuthTTL: 30m
    countAttempt: 5
    secure: false
    domain: 

redis:
    host: 192.168.5.159
    port: 6379
    db: 0

limiter:
    rps: 10
    burst: 20
    ttl: 10m